Adding coverage to ReturnsConnector
hmrc/plastic-packaging-tax-returns pull request #144
Opened 2023-02-06 11:40 UTC by mycp98

2023-02-06 15:10 UTC, liampan requested changes
Looks good, remove purplePrinter and approved :)

2023-02-06 15:10 UTC, liampan commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/util/EdgeOfSystem.scala
> +  def createUuid: UUID = UUID.randomUUID()
nice

2023-02-06 15:14 UTC, lmcewanhmrc commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/ReturnsConnectorSpec.scala
> +  private val shhLogger = mock[Logger]
noisy, but yeah needs a better name

2023-02-06 15:16 UTC, lmcewanhmrc commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/util/PurplePrint.scala
> +object PurplePrint {
would like to keep it as an easy debug tool - where best to put it? any ideas?

2023-02-06 15:33 UTC, liampan commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/util/PurplePrint.scala
> +object PurplePrint {
🤔

2023-06-12 10:38 UTC, liampan approved these changes

2023-06-19 10:51 UTC, liampan approved these changes

2023-06-27 15:28 UTC, merged