PPTP-1011 Added Nrs details to audit on subscription update
hmrc/plastic-packaging-tax-returns pull request #27
Opened 2021-08-19 14:53 UTC by kiranprakashdigital

### Description of Work carried through

- Added NrsConnector to submit the updated subscription.
- Sending the NrsDetails as part of the audit event
- Also added the processing date time to audit event

#### Check list 
 - [ ] `./precheck` was executed (Integration/Component/Unit tests)
 - [ ] `sbt scalafmt test:scalafmt` was executed
 - [ ] Required Environment Config has been amended/added
 - [ ] User Acceptance Tests (UAT) were run locally and have passed.

2021-08-19 15:59 UTC, tmc-ee requested changes

2021-08-19 15:59 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/SubscriptionControllerSpec.scala
>        "request for uk limited company subscription is valid" in {
Do we need to cover Partnerships and Scottish Partnerships in the GET subscription tests too?

2021-08-19 15:59 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/SubscriptionControllerSpec.scala
> +    "return 200 for UK Limited Company " when {
Do we need to cover Partnerships and Scottish Partnerships in the PUT subscription tests too?

2021-08-19 15:59 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/util/RetryISpec.scala
> +    "not retry" when {
Do we need to test that the retry mechanism is not invoked on successful requests?

2021-08-19 15:59 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/util/RetryISpec.scala
> +    "retry a number of times" when {
Is there an agreed number of times we should retry, or does it retry until success?

2021-08-19 15:59 UTC, tmc-ee commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/NonRepudiationConnectorISpec.scala
> +      "nrs submission fails on first attempt" in {
Do we need to test subsequent retries here? e.g. retry until success, retry N number of times?

2021-08-20 08:04 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/SubscriptionControllerSpec.scala
>        "request for uk limited company subscription is valid" in {
There is no partnership implementation in Returns repo. Probably we would need separate story to include the changes for partnership.

2021-08-20 08:05 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/controllers/SubscriptionControllerSpec.scala
> +    "return 200 for UK Limited Company " when {
There is no partnership implementation in Returns repo. Probably we would need separate story to include the changes for partnership.

2021-08-20 08:21 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/util/RetryISpec.scala
> +    "retry a number of times" when {
It tries until successful with back off delays of 1, 2, 4 seconds. After 20s the service would time out anyway.

2021-08-20 08:24 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/NonRepudiationConnectorISpec.scala
> +      "nrs submission fails on first attempt" in {
There is a test of retry until successful

2021-08-20 08:30 UTC, kiranprakashdigital commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/util/RetryISpec.scala
> +    "not retry" when {
There is a test in NonRepudiationConnectorISpec which covers to check retry to invoked only on failure.

2021-08-20 10:31 UTC, tmc-ee approved these changes

2021-08-20 12:45 UTC, RyanKellyHMRC approved these changes
I notice that we are calling the Audit Service from the ppt-returns rather than the ppt-returns-fe; this is at odds with ppt-registration where audit events are recorded at the fe. Are we concerned by this inconsistency?

2021-08-20 12:45 UTC, RyanKellyHMRC commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/NonRepudiationConnector.scala
> +class NonRepudiationConnector @Inject() (
There are a number of classes and their associated tests which are a copy and paste from ppt-reg. Is it worth created a tech debt ticket so that we might consider creation of a shared library at some point in the future?

2021-08-20 13:09 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/connectors/NonRepudiationConnector.scala
> +class NonRepudiationConnector @Inject() (
Yeah sure.. I will create a tech debt for this. I thought about it but was not sure if we were Ok to create a shared library. I will create a story and then we can have a discussion :)

2021-08-20 14:32 UTC, merged