PPTP-1459 | API to surface financial data
hmrc/plastic-packaging-tax-returns pull request #60
Opened 2022-03-10 18:02 UTC by liampan

### Description of Work carried through

API for fincails used by PPT and BTA to render Tile info

#### Check list 
 - [ ] `./precheck` was executed (Integration/Component/Unit tests)
 - [ ] `sbt scalafmt test:scalafmt` was executed
 - [ ] Required Environment Config has been amended/added
 - [ ] Links to dependencies have been included (BE/FE work)
 - [ ] User Acceptance Tests (UAT) were run locally and have passed.

2022-03-11 16:12 UTC, ajchilts commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTObligationsService.scala
>      val today: LocalDate = LocalDate.now()
Do we need to use UTC for server time difference?

2022-03-11 16:12 UTC, ajchilts commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/PPTFinancialsController.scala
> +                                   LocalDate.now(),
Do we need to use UTC for server time difference?

2022-03-11 16:12 UTC, ajchilts commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/controllers/PPTObligationsController.scala
> +        obligationsDataConnector.get(ref, appConfig.pptTaxStartDate, LocalDate.now(), ObligationStatus.OPEN).map {
Same for all references to LocalDate.now()

2022-03-11 16:52 UTC, kiranprakashdigital requested changes

2022-03-11 16:52 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
> +  val pptTaxStartDate: LocalDate = LocalDate.of(2022, 4, 1)
Should we have this value in the conf file?

2022-03-11 17:29 UTC, lmcewanhmrc requested changes

2022-03-11 17:29 UTC, lmcewanhmrc commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
> +      charges.filter(_.due.isBeforeToday).sortBy(_.due)
Don't need to sort?

2022-03-11 17:29 UTC, lmcewanhmrc commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsService.scala
> +  }
I think this method ^^^ can be simplified - let's get together and discuss

2022-03-11 17:29 UTC, lmcewanhmrc commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala
> +    "return NothingDue" when {
This is test is when there are no financials returned? Nothing due is another test where sum of amountOutstanding == 0?

2022-03-11 17:29 UTC, lmcewanhmrc commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala
> +        sut.construct(makeData()) mustBe PPTFinancials.NothingDue
Is NothingDue (None, None, None)? (Just x-ref-ing with wiki page...)

2022-03-11 17:29 UTC, lmcewanhmrc commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala
> +    }
There's possibly more test cases that should be here... but let's discuss...

2022-03-14 09:17 UTC, liampan commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala
> +        sut.construct(makeData()) mustBe PPTFinancials.NothingDue
Yes, open to better name suggestions

2022-03-14 09:46 UTC, liampan commented on test/uk/gov/hmrc/plasticpackagingtaxreturns/services/PPTFinancialsServiceSpec.scala
> +        sut.construct(makeData()) mustBe PPTFinancials.NothingDue
`NothingOutstanding` I guess is more correct?

2022-03-14 15:44 UTC, liampan commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
> +  val pptTaxStartDate: LocalDate = LocalDate.of(2022, 4, 1)
Yes to avoid duplication

2022-03-15 09:21 UTC, kiranprakashdigital commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
> +  val pptTaxStartDate: LocalDate = LocalDate.of(2022, 4, 1)
Can you move it to conf file, we have something similar in registration-frontend

2022-03-15 09:42 UTC, lmcewanhmrc approved these changes

2022-03-15 09:52 UTC, liampan commented on app/uk/gov/hmrc/plasticpackagingtaxreturns/config/AppConfig.scala
> +  val pptTaxStartDate: LocalDate = LocalDate.of(2022, 4, 1)
But its not configurable per env? is that not just adding it for the sake of adding it?

2022-03-15 10:00 UTC, merged